### ISSUE TITLE
Members

### ISSUE THREAD

**Issue by romainGuiet** [gaetancollaud/fablab-api#20]
Hi Gaétan,
In the "users" section, could you add a summary containing ,  the number of users :
- with a "negative" account 
- with a "postive" account 
- with a "neutral" account 
- in total 

Cheers,
Romain

**Comment by gaetancollaud** [comment]
Hi,

I will do this when I have 5 mins.

Cheers,
Gaétan

**Comment by gaetancollaud** [comment]
Done in release fablab-manager-2.0.6. You can try it out at http://collaud2.collaud.me/fablab-manager/#/users by clicking on "Detail".

A added  a summary for the balances and the subscriptions.
